[Unit]
Wants=encrypt-k3s-credential.service
After=encrypt-k3s-credential.service
AssertPathExists=/etc/rancher/k3s/k3s-token
After=network-online.target
After=initial-bootc-switch.service

[Service]
LoadCredentialEncrypted=k3s-token:/etc/rancher/k3s/k3s-token
Environment=K3S_TOKEN_FILE=%d/k3s-token

[Install]
WantedBy=multi-user.target
